name: lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ShellCheck install.sh
        run: shellcheck --severity=warning install.sh  # preinstalled on ubuntu-latest
      - name: zsh syntax check
        run: sudo apt-get install -y -qq zsh && zsh -n zsh/.zshrc
